# Generated by Django 5.2.7 on 2026-03-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('tags_from_user', models.TextField(blank=True, help_text='Comma-separated tags from user', null=True)),
                ('class_level', models.CharField(blank=True, help_text='e.g., LKG, UKG, Class 1', max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, help_text='e.g., 2025', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('last_searched_at', models.DateTimeField(blank=True, null=True)),
                ('search_requests', models.ManyToManyField(blank=True, related_name='keywords', to='api.searchrequest')),
            ],
        ),
    ]
