# Generated by Django 5.2.7 on 2026-03-31 10:11

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("FREE", "Free"),
                            ("JUNIOR", "Junior"),
                            ("MASTER", "Master"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=50)),
                (
                    "course_content_percentage",
                    models.IntegerField(
                        help_text="Percentage of course content accessible (60 for FREE, 100 for others)"
                    ),
                ),
                ("has_activities", models.BooleanField(default=False)),
                ("has_quizzes", models.BooleanField(default=False)),
                ("has_games", models.BooleanField(default=False)),
                ("shows_ads", models.BooleanField(default=True)),
                ("allows_multiple_profiles", models.BooleanField(default=False)),
                (
                    "master_discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Discount amount for MASTER plan (₹20 default)",
                        max_digits=10,
                    ),
                ),
                (
                    "yearly_discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage discount for yearly subscriptions (for future use)",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "mobile",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "board",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("NURSERY", "Nursery"),
                            ("LKG", "LKG"),
                            ("UKG", "UKG"),
                            ("1", "Class 1"),
                            ("2", "Class 2"),
                            ("3", "Class 3"),
                            ("4", "Class 4"),
                            ("5", "Class 5"),
                            ("6", "Class 6"),
                            ("7", "Class 7"),
                            ("8", "Class 8"),
                            ("9", "Class 9"),
                            ("10", "Class 10"),
                            ("11", "Class 11"),
                            ("12", "Class 12"),
                            ("BC5", "Below Class 5th"),
                        ],
                        help_text="Target grade for this course",
                        max_length=10,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="courses/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["grade", "title"],
                "indexes": [
                    models.Index(
                        fields=["grade", "is_active"],
                        name="authenticat_grade_4d41d5_idx",
                    ),
                    models.Index(
                        fields=["status"], name="authenticat_status_c0ee2e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, help_text="Display order"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon name or emoji", max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="authentication.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        choices=[("MONTHLY", "Monthly"), ("YEARLY", "Yearly")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "renewal_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Next renewal date for auto-renewal",
                        null=True,
                    ),
                ),
                ("is_auto_renew", models.BooleanField(default=True)),
                (
                    "monthly_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly amount for this subscription",
                        max_digits=10,
                    ),
                ),
                (
                    "total_amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "pricing_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NURSERY", "Nursery"),
                            ("LKG", "LKG"),
                            ("UKG", "UKG"),
                            ("1", "Class 1"),
                            ("2", "Class 2"),
                            ("3", "Class 3"),
                            ("4", "Class 4"),
                            ("5", "Class 5"),
                            ("6", "Class 6"),
                            ("7", "Class 7"),
                            ("8", "Class 8"),
                            ("9", "Class 9"),
                            ("10", "Class 10"),
                            ("11", "Class 11"),
                            ("12", "Class 12"),
                            ("BC5", "Below Class 5th"),
                        ],
                        help_text="Grade used for pricing (Nursery/LKG/UKG for JUNIOR plan)",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="authentication.plan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Syllabus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "academic_year",
                    models.CharField(
                        blank=True, help_text="e.g., 2024-25", max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabi",
                        to="authentication.subject",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Syllabi",
                "ordering": ["-academic_year"],
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "chapter_number",
                    models.PositiveIntegerField(
                        db_index=True, help_text="Chapter sequence number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "syllabus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="authentication.syllabus",
                    ),
                ),
            ],
            options={
                "ordering": ["chapter_number"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_day",
                    models.PositiveIntegerField(help_text="Starting day number"),
                ),
                ("end_day", models.PositiveIntegerField(help_text="Ending day number")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["start_day"],
            },
        ),
        migrations.CreateModel(
            name="TaskItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("VIDEO", "Video"),
                            ("QUIZ", "Quiz"),
                            ("GAME", "Game"),
                            ("ACTIVITY", "Activity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "day_number",
                    models.PositiveIntegerField(
                        help_text="Specific day number within the task range"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order within the same day"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="authentication.task",
                    ),
                ),
            ],
            options={
                "ordering": ["day_number", "order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_url", models.URLField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                        ],
                        default="EASY",
                        max_length=20,
                    ),
                ),
                ("instructions", models.TextField(blank=True)),
                (
                    "task_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_data",
                        to="authentication.taskitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instructions", models.TextField()),
                (
                    "materials_needed",
                    models.TextField(
                        blank=True, help_text="Materials required for activity"
                    ),
                ),
                (
                    "estimated_time",
                    models.PositiveIntegerField(help_text="Estimated time in minutes"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="activity_images/"
                    ),
                ),
                (
                    "task_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_data",
                        to="authentication.taskitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quiz_type",
                    models.CharField(
                        choices=[
                            ("QUESTION_OPTIONS", "Question Options"),
                            ("MATCH_MAKING", "Match Making"),
                        ],
                        default="QUESTION_OPTIONS",
                        max_length=20,
                    ),
                ),
                ("questions", models.JSONField(help_text="Array of question objects")),
                (
                    "passing_score",
                    models.PositiveIntegerField(
                        default=60, help_text="Percentage required to pass"
                    ),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        blank=True, help_text="Time limit in minutes", null=True
                    ),
                ),
                (
                    "shuffle_questions",
                    models.BooleanField(
                        default=True, help_text="Randomize question order"
                    ),
                ),
                (
                    "task_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_data",
                        to="authentication.taskitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Display order within chapter",
                    ),
                ),
                (
                    "search_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("last_searched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="authentication.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="authentication.topic",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_for",
                    models.CharField(
                        choices=[("SELF", "Self"), ("CHILD", "Child")], max_length=10
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "profile_picture",
                    models.ImageField(null=True, upload_to="profile_pics/"),
                ),
                (
                    "mother_tongue",
                    models.CharField(
                        choices=[
                            ("EN", "English"),
                            ("HI", "Hindi"),
                            ("TA", "Tamil"),
                            ("TE", "Telugu"),
                            ("ML", "Malayalam"),
                            ("KN", "Kannada"),
                            ("BN", "Bengali"),
                            ("MR", "Marathi"),
                            ("GU", "Gujarati"),
                            ("UR", "Urdu"),
                            ("OR", "Odia"),
                            ("OT", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        choices=[
                            ("2.0", "2.0 years"),
                            ("2.5", "2.5 years"),
                            ("3.0", "3.0 years"),
                            ("3.5", "3.5 years"),
                            ("4.0", "4.0 years"),
                            ("4.5", "4.5 years"),
                            ("5.0", "5.0 years"),
                            ("5.5", "5.5 years"),
                            ("6.0", "6.0 years"),
                        ],
                        help_text="Child's age (2.0 to 6.0 years)",
                        max_length=5,
                    ),
                ),
                ("is_studying", models.BooleanField()),
                (
                    "reason_not_studying",
                    models.TextField(
                        blank=True, help_text="Reason if user is not in school"
                    ),
                ),
                (
                    "school_type",
                    models.CharField(
                        blank=True,
                        choices=[("PRIVATE", "Private"), ("GOVERNMENT", "Government")],
                        max_length=20,
                    ),
                ),
                ("school_name", models.CharField(blank=True, max_length=255)),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NURSERY", "Nursery"),
                            ("LKG", "LKG"),
                            ("UKG", "UKG"),
                            ("1", "Class 1"),
                            ("2", "Class 2"),
                            ("3", "Class 3"),
                            ("4", "Class 4"),
                            ("5", "Class 5"),
                            ("6", "Class 6"),
                            ("7", "Class 7"),
                            ("8", "Class 8"),
                            ("9", "Class 9"),
                            ("10", "Class 10"),
                            ("11", "Class 11"),
                            ("12", "Class 12"),
                            ("BC5", "Below Class 5th"),
                        ],
                        max_length=10,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("FREE", "Free"),
                            ("JUNIOR", "Junior"),
                            ("MASTER", "Master"),
                        ],
                        default="FREE",
                        max_length=10,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profiles",
                        to="authentication.subscription",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfileSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("NURSERY", "Nursery"),
                            ("LKG", "LKG"),
                            ("UKG", "UKG"),
                            ("1", "Class 1"),
                            ("2", "Class 2"),
                            ("3", "Class 3"),
                            ("4", "Class 4"),
                            ("5", "Class 5"),
                            ("6", "Class 6"),
                            ("7", "Class 7"),
                            ("8", "Class 8"),
                            ("9", "Class 9"),
                            ("10", "Class 10"),
                            ("11", "Class 11"),
                            ("12", "Class 12"),
                            ("BC5", "Below Class 5th"),
                        ],
                        help_text="Grade for pricing calculation (Nursery/LKG/UKG)",
                        max_length=10,
                    ),
                ),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly price for this profile's grade",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_subscriptions",
                        to="authentication.subscription",
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_subscription",
                        to="authentication.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["subscription", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=50)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("DISAPPROVED", "Disapproved"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.URLField(max_length=500)),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "channel_title",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("duration", models.CharField(blank=True, max_length=20, null=True)),
                ("view_count", models.BigIntegerField(blank=True, null=True)),
                ("like_count", models.BigIntegerField(blank=True, null=True)),
                ("comment_count", models.BigIntegerField(blank=True, null=True)),
                ("tags_from_video", models.TextField(blank=True, null=True)),
                ("category_id", models.CharField(blank=True, max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="authentication.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["-view_count"],
            },
        ),
        migrations.CreateModel(
            name="TaskVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_data",
                        to="authentication.taskitem",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        limit_choices_to={"approval_status": "APPROVED"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.videoresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("NURSERY", "Nursery"),
                            ("LKG", "LKG"),
                            ("UKG", "UKG"),
                            ("1", "Class 1"),
                            ("2", "Class 2"),
                            ("3", "Class 3"),
                            ("4", "Class 4"),
                            ("5", "Class 5"),
                            ("6", "Class 6"),
                            ("7", "Class 7"),
                            ("8", "Class 8"),
                            ("9", "Class 9"),
                            ("10", "Class 10"),
                            ("11", "Class 11"),
                            ("12", "Class 12"),
                            ("BC5", "Below Class 5th"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Monthly price in ₹", max_digits=10
                    ),
                ),
                (
                    "yearly_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Yearly price in ₹ (calculated: monthly * 12)",
                        max_digits=10,
                    ),
                ),
                (
                    "yearly_discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage discount for yearly subscription (for future use)",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing",
                        to="authentication.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["plan", "grade"],
                "unique_together": {("plan", "grade")},
            },
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["course", "is_active", "order"],
                name="authenticat_course__9c3749_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("course", "name"), name="uniq_subject_course_name"
            ),
        ),
        migrations.AddIndex(
            model_name="syllabus",
            index=models.Index(
                fields=["subject", "is_active"], name="authenticat_subject_bb4d5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syllabus",
            index=models.Index(
                fields=["academic_year"], name="authenticat_academi_3b6b97_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="syllabus",
            constraint=models.UniqueConstraint(
                fields=("subject", "title", "academic_year"),
                name="uniq_syllabus_subject_title_version",
            ),
        ),
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(
                fields=["syllabus", "is_active", "chapter_number"],
                name="authenticat_syllabu_27308f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="chapter",
            constraint=models.UniqueConstraint(
                fields=("syllabus", "chapter_number"),
                name="uniq_chapter_syllabus_chapter_number",
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["chapter", "is_active", "order"],
                name="authenticat_chapter_d397cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(fields=["status"], name="authenticat_status_30c49b_idx"),
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.UniqueConstraint(
                fields=("chapter", "order"), name="uniq_topic_chapter_order"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="profilesubscription",
            unique_together={("subscription", "profile")},
        ),
        migrations.AlterUniqueTogether(
            name="videoresult",
            unique_together={("topic", "video_id")},
        ),
    ]
