# Generated by Django 5.2.7 on 2026-03-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="syllabus",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="attachments",
            field=models.JSONField(
                blank=True, default=list, help_text="List of attachment metadata/URLs"
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Rich text or markdown notes for this topic"
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="video_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
